title: 김형숙
tagline: HYungsook Kim
description: 한양대학교 교수
url: 'https://hyungsook.netlify.app/'
baseurl:
author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''

theme: jekyll-theme-hydeout
